// src/lib/cosmetics.js
export const BADGES = [
	{
		id: "badge-star",
		name: "Selo Estrela",
		kind: "badge",
		price: 0,
		owned: true,
		equipped: true,
	},
	{ id: "badge-emerald", name: "Selo Esmeralda", kind: "badge", price: 20 },
	{ id: "badge-bronze", name: "Selo Bronze", kind: "badge", price: 36 },
	{ id: "badge-silver", name: "Selo Prata", kind: "badge", price: 64 },
	{ id: "badge-gold", name: "Selo Ouro", kind: "badge", price: 116 },
	{ id: "badge-ruby", name: "Selo Rubi", kind: "badge", price: 207 },
	{ id: "badge-sapphire", name: "Selo Safira", kind: "badge", price: 372 },
	{ id: "badge-onyx", name: "Selo Ônix", kind: "badge", price: 668 },
	{ id: "badge-diamond", name: "Selo Diamante", kind: "badge", price: 1198 },
	{ id: "badge-platinum", name: "Selo Platina", kind: "badge", price: 2150 },
	{ id: "badge-titanium", name: "Selo Titânio", kind: "badge", price: 3858 },
	{ id: "badge-master", name: "Selo Mestre", kind: "badge", price: 6923 },
	{ id: "badge-legend", name: "Selo Lendário", kind: "badge", price: 12423 },
	{ id: "badge-grand", name: "Selo Grão-Mestre", kind: "badge", price: 22291 },
	{ id: "badge-immortal", name: "Selo Imortal", kind: "badge", price: 40000 },
	{
		id: "badge-celestial",
		name: "Selo Celestial",
		kind: "badge",
		price: 50000,
	},
];

export const BORDERS = [
	{ id: "border-neon", name: "Borda Neon", kind: "border", price: 80 },
	{ id: "border-gold", name: "Borda Dourada", kind: "border", price: 110 },
	{ id: "border-emerald", name: "Borda Esmeralda", kind: "border", price: 152 },
	{ id: "border-purple", name: "Borda Violeta", kind: "border", price: 210 },
	{ id: "border-prism", name: "Borda Prisma", kind: "border", price: 290 },
	{ id: "border-platina", name: "Borda Platina", kind: "border", price: 400 },
	{ id: "border-arcane", name: "Borda Arcana", kind: "border", price: 552 },
	{
		id: "border-obsidian",
		name: "Borda Obsidiana",
		kind: "border",
		price: 761,
	},
	{ id: "border-crystal", name: "Borda Cristal", kind: "border", price: 1051 },
	{
		id: "border-horizon",
		name: "Borda Horizonte",
		kind: "border",
		price: 1450,
	},
	{ id: "border-royal", name: "Borda Real", kind: "border", price: 2000 },
	{ id: "border-phantom", name: "Borda Fantasma", kind: "border", price: 2759 },
	{ id: "border-glitch", name: "Borda Glitch", kind: "border", price: 3807 },
	{ id: "border-lava", name: "Borda Lava", kind: "border", price: 5253 },
	{ id: "border-arctic", name: "Borda Ártica", kind: "border", price: 7248 },
	{ id: "border-eclipse", name: "Borda Eclipse", kind: "border", price: 10000 },
	{
		id: "border-starlight",
		name: "Borda Estelar",
		kind: "border",
		price: 13797,
	},
	{ id: "border-cosmos", name: "Borda Cosmos", kind: "border", price: 19037 },
	{ id: "border-eternal", name: "Borda Eterna", kind: "border", price: 26265 },
	{ id: "border-jade", name: "Borda Jade", kind: "border", price: 36239 },
	{
		id: "border-amethyst",
		name: "Borda Ametista",
		kind: "border",
		price: 50000,
	},
];

export const BGS = [
	{ id: "bg-aurora", name: "Fundo Aurora", kind: "bg", price: 90 },
	{ id: "bg-dusk", name: "Fundo Crepúsculo", kind: "bg", price: 120 },
	{ id: "bg-matrix", name: "Fundo Matrix", kind: "bg", price: 161 },
	{ id: "bg-ocean", name: "Fundo Oceano", kind: "bg", price: 215 },
	{ id: "bg-sakura", name: "Fundo Sakura", kind: "bg", price: 287 },
	{ id: "bg-nebula", name: "Fundo Nébulas", kind: "bg", price: 384 },
	{ id: "bg-supernova", name: "Fundo Supernova", kind: "bg", price: 514 },
	{ id: "bg-eternum", name: "Fundo Eternum", kind: "bg", price: 687 },
	{ id: "bg-monolith", name: "Fundo Monólito", kind: "bg", price: 918 },
	{ id: "bg-glacier", name: "Fundo Geleira", kind: "bg", price: 1227 },
	{ id: "bg-desert", name: "Fundo Deserto", kind: "bg", price: 1641 },
	{ id: "bg-rainforest", name: "Fundo Floresta", kind: "bg", price: 2194 },
	{ id: "bg-cybergrid", name: "Fundo Cybergrid", kind: "bg", price: 2933 },
	{ id: "bg-vapor", name: "Fundo Vaporwave", kind: "bg", price: 3921 },
	{ id: "bg-midnight", name: "Fundo Meia-noite", kind: "bg", price: 5241 },
	{ id: "bg-sunrise", name: "Fundo Amanhecer", kind: "bg", price: 7007 },
	{ id: "bg-sunset", name: "Fundo Pôr do Sol", kind: "bg", price: 9368 },
	{ id: "bg-galaxy", name: "Fundo Galáxia", kind: "bg", price: 12523 },
	{ id: "bg-cyberpunk", name: "Fundo Cyberpunk", kind: "bg", price: 16742 },
	{ id: "bg-neoncity", name: "Fundo Neon City", kind: "bg", price: 22381 },
	{
		id: "bg-forestnight",
		name: "Fundo Floresta à Noite",
		kind: "bg",
		price: 29921,
	},
	{
		id: "bg-holo",
		name: "Fundo Holográfico (Lendário)",
		kind: "bg",
		price: 40000,
	},
];
